events {
    worker_connections 1024;
}

http {
    server {
        # O Gateway vai rodar na porta 8080
        listen 80;

        # Configuração de CORS centralizada no Gateway
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization' always;

        if ($request_method = 'OPTIONS') {
            return 204;
        }

        # 1. Tudo que for cálculo vai para o Python
        location /api/heat-exchangers/ {
            proxy_pass http://py_service:8000;
        }

        location /api/external-flow/ {
            proxy_pass http://py_service:8000;
        }

        # 2. Tudo que for notas/banco de dados vai para o C#
        location /api/notes/ {
            proxy_pass http://csharp_api:8080; # Ajuste para a porta interna do seu C#
        }

        location /api/productivity {
            proxy_pass http://csharp_api:8080;
        }

        # 3. Futuro: Autenticação, Geração de PDF, etc.
        # location /api/pdf/ { ... }
    }
}
