export const SolverLabels: Record<string, string> = {
    "linear-interpolation":    "Linear Interpolation",
    "heat-transfer-rate":           "Heat Transfer Rate (Newton's Law)",
    "churchill-bernstein-1":  "Cylinder Cross-Flow Correlation (Churchill-Bernstein)",
    "churchill-bernstein-2":  "Cylinder Cross-Flow Correlation (Churchill-Bernstein) Extended",
    "churchill-ozoe":         "Churchill–Ozoe Correlation",
    "internal-flow-avg-temp-q-const":     "Internal Flow — Average Temperature (q'' constant)",
    "internal-flow-avg-temp-ts-const":    "Internal Flow — Average Temperature (Ts constant)",
    "cross-flow-energy-balance-ts-const":    "Cross Flow — Energy Balance (Ts constant)",
    "fin-parameters":              "Fin — Parameters m and M",
    "fin-excess-temp":              "Fin — Excess Temperature θ and θb",
    "fin-heat-transfer-case-b":    "Fin — Heat Transfer Case B (Adiabatic Tip)",
    "fin-heat-transfer-case-a":    "Fin — Heat Transfer Case A (Convective Tip)",
    "fin-heat-transfer-case-c":    "Fin — Heat Transfer Case C (Prescribed Temperature)",
    "fin-heat-transfer-case-d":    "Fin — Heat Transfer Case D (Infinite Fin)",
    "fin-temp-dist-case-b": "Fin — Temperature Distribution Case B",
    "fin-temp-dist-case-a": "Fin — Temperature Distribution Case A",
    "fin-temp-dist-case-c": "Fin — Temperature Distribution Case C",
    "fin-temp-dist-case-d": "Fin — Temperature Distribution Case D",
    "fin-rect-profile-efficiency":             "Fin — Efficiency (Rectangular Profile, Eq. 3.94)",
};
