export const SolverLabels: Record<string, string> = {
    "linear-interpolation":    "Linear Interpolation",
    "heat-transfer-rate":           "Heat Transfer Rate (Newton's Law)",
    "churchill-bernstein-1":  "Cylinder Cross-Flow Correlation (Churchill-Bernstein)",
    "churchill-bernstein-2":  "Cylinder Cross-Flow Correlation (Churchill-Bernstein) Extended",
    "churchill-ozoe":         "Churchill–Ozoe Correlation",
    "internal-flow-avg-temp-q-const":     "Internal Flow — Average Temperature (q'' constant)",
    "internal-flow-avg-temp-ts-const":    "Internal Flow — Average Temperature (Ts constant)",
    "cross-flow-energy-balance-ts-const":    "Cross Flow — Energy Balance (Ts constant)",
    "fin-parameters":              "Fin — Parameters m and M",
    "fin-excess-temp":              "Fin — Excess Temperature θ and θb",
    "fin-heat-transfer-case-b":    "Fin — Heat Transfer Case B (Adiabatic Tip)",
    "fin-heat-transfer-case-a":    "Fin — Heat Transfer Case A (Convective Tip)",
    "fin-heat-transfer-case-c":    "Fin — Heat Transfer Case C (Prescribed Temperature)",
    "fin-heat-transfer-case-d":    "Fin — Heat Transfer Case D (Infinite Fin)",
    "fin-temp-dist-case-b": "Fin — Temperature Distribution Case B",
    "fin-temp-dist-case-a": "Fin — Temperature Distribution Case A",
    "fin-temp-dist-case-c": "Fin — Temperature Distribution Case C",
    "fin-temp-dist-case-d": "Fin — Temperature Distribution Case D",
    "fin-rect-profile-efficiency":             "Fin — Efficiency (Rectangular Profile, Eq. 3.94)",
    // Tabela 7.9 Incropera (atalho \7.xx)
    "7.19": "7.19",
    "7.20": "7.20",
    "7.21": "7.21",
    "7.22": "7.22",
    "7.23": "7.23",
    "7.24": "7.24",
    "7.29": "7.29",
    "7.30": "7.30",
    "7.32": "7.32",
    "7.34": "7.34",
    "7.35": "7.35",
    "7.36": "7.36",
    "7.38": "7.38",
    "7.40": "7.40",
    "7.52": "7.52",
    "7.53": "7.53",
    "7.54": "7.54",
    "7.56": "7.56",
    "7.57": "7.57",
    "7.60": "7.60",
    "7.64": "7.64",
    "7.70-7.72": "7.70–7.72",
    "7.73-7.75": "7.73–7.75",
    "7.76-7.78": "7.76–7.78",
    "7.79-7.81": "7.79–7.81",
    "7.44": "7.44 → 7.52",
    "7.63": "7.63 → 7.64",
};
